
eureka:
  instance:
        prefer-ip-address: true
  client:
    serviceUrl:

      defaultZone: http://127.0.0.1:8761/eureka/
server:
  port: 8889

spring:
  application:
    name: service-test
  datasource:
    #配置Mysql连接信息
    url: jdbc:mysql://localhost:3306/ssh?characterEncoding=utf8
    username: root
    password: 111111
    #mongodb数据配置
  data:
#    mongodb:
#       host: 127.0.0.1
#       port: 27017
#       name: test

#    elasticsearch:
#      cluster-name:
#      cluster-nodes: 47.93.185.155:9200
#      username: elastic
#      password: dYNLcZQndniuiXDfjupr9yoD
  jpa:
    #使用数据源
    database: MYSQL
    #是否打印日志
    show-sql: true
  #Hibernate ddl auto (validate|create|create-drop|update)
    hibernate:
      #加载hibernate自动更新数据库结构
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
#配置redis连接信息
redis:
  # database: 1
    host: 192.168.1.214
    port: 6379
    pool:
      # 连接池中的最大空闲连接
      max-idle: 8
      # 连接池中的最小空闲连接
      min-idle: 0
      # 连接池最大连接数（使用负值表示没有限制）
      max-active: 8
      # 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-wait: -1